document.addEventListener('DOMContentLoaded', async () => {
  const page = document.body.dataset.adminPage; if (!page) return;
  try { const products = await loadProducts(); if (page === 'dashboard') dashboard(products); if (page === 'products') productsPage(products); } catch (error) { document.querySelector('main').innerHTML = `<p class="error">${error.message}</p>`; }
});
function dashboard(products) { const low = products.filter(product => totalStock(product) <= 3); document.querySelector('[data-admin-content]').innerHTML = `<h1>Обзор магазина</h1><div class="stats"><div class="stat"><span>Товары</span><strong>${products.length}</strong></div><div class="stat"><span>Категории</span><strong>${getCategories(products).length}</strong></div><div class="stat"><span>Заказы</span><strong>${loadOrders().length}</strong></div><div class="stat"><span>Низкий остаток</span><strong>${low.length}</strong></div></div><section class="admin-card"><h2>Товары с низким остатком</h2>${low.length ? `<ul>${low.map(item=>`<li>${item.name} — ${totalStock(item)} шт.</li>`).join('')}</ul>` : '<p>Таких товаров нет.</p>'}</section>`; }
function productsPage(products) {
  const root = document.querySelector('[data-admin-content]');
  function render() { root.innerHTML = `<div class="section-head"><div><h1>Товары</h1><p>Все изменения сохраняются только в этом браузере.</p></div><button class="button" data-create>+ Добавить товар</button></div><div class="admin-card table-wrap"><table class="admin-table"><thead><tr><th>Товар</th><th>Цена</th><th>Категория</th><th>Остаток</th><th>Действия</th></tr></thead><tbody>${products.map(product=>`<tr><td>${product.name}</td><td>${money(product.price)}</td><td>${categoryTitle(product.category)}</td><td>${totalStock(product)}</td><td><div class="admin-actions"><button class="button button--secondary" data-edit="${product.id}">Редактировать</button><button class="button button--danger" data-delete="${product.id}">Удалить</button></div></td></tr>`).join('')}</tbody></table></div><div class="modal" data-modal><div class="modal__content"><div class="modal__head"><h2 data-modal-title>Товар</h2><button class="icon-button" data-close aria-label="Закрыть">×</button></div><form class="form-grid" data-product-form></form></div></div>`; bind(); }
  function bind() { root.querySelector('[data-create]').onclick=()=>form(); root.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>form(products.find(p=>p.id===Number(button.dataset.edit)))); root.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>{const item=products.find(p=>p.id===Number(button.dataset.delete)); if(confirm(`Удалить «${item.name}»?`)){products=products.filter(p=>p!==item);saveProducts(products);render();}}); }
  function form(item) { const modal=root.querySelector('[data-modal]'); const f=modal.querySelector('form'); modal.classList.add('is-open'); modal.querySelector('[data-close]').onclick=()=>modal.classList.remove('is-open'); const value=(key, fallback='')=>item ? (item[key] ?? fallback) : fallback; f.innerHTML=`<div class="form-grid form-grid--two"><label class="field">Название<input required class="input" name="name" value="${value('name')}"></label><label class="field">Цена<input required class="input" name="price" type="number" min="0" value="${value('price')}"></label><label class="field">Старая цена<input class="input" name="oldPrice" type="number" min="0" value="${value('oldPrice')}"></label><label class="field">Категория<input required class="input" name="category" value="${value('category','t-shirts')}"></label><label class="field">Размеры через запятую<input required class="input" name="sizes" value="${item?item.sizes.join(', '):'S, M, L'}"></label><label class="field">Цвета через запятую<input required class="input" name="colors" value="${item?item.colors.join(', '):'Black'}"></label><label class="field">Количество для каждого размера<input required class="input" name="quantity" type="number" min="0" value="${item?Math.max(...Object.values(item.stock)):0}"></label><label class="field">Путь к изображению<input class="input" name="image" value="${item?item.images[0]:'assets/images/tshirt.svg'}"></label></div><label class="field">Описание<textarea required class="textarea" name="description">${value('description')}</textarea></label><label><input type="checkbox" name="featured" ${item?.featured?'checked':''}> Показывать на главной</label><button class="button">Сохранить</button>`; f.onsubmit=event=>{event.preventDefault();const d=Object.fromEntries(new FormData(f));const sizes=d.sizes.split(',').map(x=>x.trim()).filter(Boolean);const product={id:item?.id||Date.now(),name:d.name,slug:d.name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),price:Number(d.price),oldPrice:d.oldPrice?Number(d.oldPrice):null,category:d.category,description:d.description,images:[d.image],sizes,colors:d.colors.split(',').map(x=>x.trim()).filter(Boolean),stock:Object.fromEntries(sizes.map(s=>[s,Number(d.quantity)])),featured:d.featured==='on',new:item?.new||false};if(item)products=products.map(p=>p.id===item.id?product:p);else products.push(product);saveProducts(products);modal.classList.remove('is-open');render();}; }
  render();
}
