document.addEventListener('DOMContentLoaded', async () => {
  const root = document.querySelector('[data-cart-page]'); if (!root) return;
  try {
    const [products, store] = await Promise.all([loadProducts(), loadStore()]);
    function render() {
      const cart = loadCart(); const rows = cart.map(item => ({ ...item, product: products.find(product => product.id === item.productId) })).filter(item => item.product);
      if (!rows.length) { root.innerHTML = '<div class="empty-state"><h2>Ваша корзина пуста</h2><p>Добавьте вещи из каталога, и они появятся здесь.</p><br><a class="button" href="catalog.html">Перейти в каталог</a></div>'; return; }
      const total = rows.reduce((sum, item) => sum + item.product.price * item.quantity, 0);
      root.innerHTML = `<div class="cart-layout"><section><h1>Корзина</h1><div class="cart-items">${rows.map(item => `<article class="cart-item"><img src="${assetPath(item.product.images[0])}" alt="${item.product.name}"><div class="cart-item__info"><strong>${item.product.name}</strong><span>Размер: ${item.size}</span><strong>${money(item.product.price, store.currency)}</strong><div class="quantity"><button data-change="-1" data-key="${item.productId}|${item.size}" aria-label="Уменьшить количество">−</button><span>${item.quantity}</span><button data-change="1" data-key="${item.productId}|${item.size}" aria-label="Увеличить количество">+</button><button class="button button--secondary" data-remove="${item.productId}|${item.size}">Удалить</button></div></div></article>`).join('')}</div></section><aside class="order-box"><h2>Оформление заказа</h2><div class="total"><span>Итого</span><span>${money(total, store.currency)}</span></div><form data-order-form><label class="field">Имя<input required class="input" name="name"></label><label class="field">Телефон<input required class="input" name="phone" type="tel"></label><label class="field">Город<input required class="input" name="city"></label><label class="field">Доставка<select required class="select" name="delivery"><option value="Новая почта">Новая почта</option><option value="Самовывоз">Самовывоз</option></select></label><label class="field">Комментарий<textarea class="textarea" name="comment"></textarea></label><button class="button">Оформить тестовый заказ</button><p data-order-message></p></form></aside></div>`;
      root.querySelectorAll('[data-change]').forEach(button => button.addEventListener('click', () => change(button.dataset.key, Number(button.dataset.change)))); root.querySelectorAll('[data-remove]').forEach(button => button.addEventListener('click', () => remove(button.dataset.remove)));
      root.querySelector('[data-order-form]').addEventListener('submit', order);
    }
    function change(key, difference) { const [id, size] = key.split('|'); const cart = loadCart(); const item = cart.find(row => row.productId === Number(id) && row.size === size); item.quantity += difference; saveCart(cart.filter(row => row.quantity > 0)); updateCartCount(); render(); }
    function remove(key) { const [id, size] = key.split('|'); saveCart(loadCart().filter(row => !(row.productId === Number(id) && row.size === size))); updateCartCount(); render(); }
    function order(event) { event.preventDefault(); const order = { id: Date.now(), date: new Date().toISOString(), customer: Object.fromEntries(new FormData(event.currentTarget)), items: loadCart() }; saveOrders([...loadOrders(), order]); saveCart([]); updateCartCount(); root.innerHTML = '<div class="empty-state"><h2>Заказ принят!</h2><p>Это demo-заказ: он сохранён в LocalStorage и виден в админке.</p><br><a class="button" href="catalog.html">Продолжить покупки</a></div>'; }
    render();
  } catch (error) { root.innerHTML = `<p class="error">${error.message}</p>`; }
});
